#
# Define LINUX if running on Linux
#
IF(CMAKE_SYSTEM_NAME STREQUAL Linux)
  SET(LINUX "YES")
ENDIF(CMAKE_SYSTEM_NAME STREQUAL Linux)

#
# Define FREEBSD if running on FreeBSD
#
IF(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
  SET(FREEBSD "YES")
ENDIF(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
