<!--  $Id$  -->
<?
$cur_date = getdate(time());
?>
<div id=footer>
    Copyright &#169; 2004-<?=$cur_date['year'] ?> Intel Corporation --
    <a href="http://www.intel.com/sites/corporate/tradmarx.htm">
    Legal Information</a> and
    <a href="http://www.intel.com/sites/corporate/privacy.htm">
    Privacy Policy</a>
</div>
<!--
<div id=logo>
    <a intel href=http://www.intel.com>
    <img src="<?=$G['MYLOGO']?>" border=0></a>
</div>
-->

</body>
</html>
